In [1]:
import pandas as pd

import numpy as np

import re

In [2]:
config_prefix = ['TI', 'TR', 'BR', 'BI']

config_algo_names = ['BinarySearch', 'BubbleSort', 'Factorial', 'Fibonacci', 'IntegerBinary', 'MultiplyMatrix', 'PrimeFactors', 'ReverseString']

config_id_variable = "CASE"

config_answer_variables = [
    ['TI21_01', 'TR21_01', 'BR21_01', 'BI21_01'],
    ['TI22_01', 'TR22_01', 'BR22_01', 'BI22_01'],
    ['TI23_01', 'TR23_01', 'BR23_01', 'BI23_01'],
    ['TI24_01', 'TR24_01', 'BR24_01', 'BI24_01'],
    ['TI25_01', 'TR25_01', 'BR25_01', 'BI25_01'],
    ['TI26_01', 'TR26_01', 'BR26_01', 'BI26_01'],
    ['TI27_01', 'TR27_01', 'BR27_01', 'BI27_01'],
    ['TI28_01', 'TR28_01', 'BR28_01', 'BI28_01'],
]

config_time_variables = [
    ['TIME011','TIME083','TIME035','TIME059'],
    ['TIME038','TIME014','TIME062','TIME086'],
    ['TIME065','TIME041','TIME086','TIME017'],
    ['TIME092','TIME068','TIME020','TIME044'],
    ['TIME023','TIME095','TIME047','TIME071'],
    ['TIME050','TIME026','TIME074','TIME098'],
    ['TIME077','TIME053','TIME0101','TIME029'],
    ['TIME0104','TIME080','TIME032','TIME056'],
]

config_click_variables = [
    ['VC01_01', 'VA01_01', 'VB01_01', 'VD01_01'],
    ['VC01_01', 'VA01_01', 'VB01_01', 'VD01_01'],
    ['VC01_01', 'VA01_01', 'VB01_01', 'VD01_01'],
    ['VC01_01', 'VA01_01', 'VB01_01', 'VD01_01'],
    ['VC01_01', 'VA01_01', 'VB01_01', 'VD01_01'],
    ['VC01_01', 'VA01_01', 'VB01_01', 'VD01_01'],
    ['VC01_01', 'VA01_01', 'VB01_01', 'VD01_01'],
    ['VC01_01', 'VA01_01', 'VB01_01', 'VD01_01'],
]


config_answer_patterns = [
    ['.*3.*', '.*3.*', '.*3.*', '.*3.*'],
    ['.*3.*16.*23.*42.*61.*75.*536.*','.*3.*16.*23.*42.*61.*75.*536.*','.*3.*16.*23.*42.*61.*75.*536.*','.*3.*16.*23.*42.*61.*75.*536.*'],
    ['.*6.*','.*6.*','.*120.*','.*120.*'],
    ['.*2.*', '.*2.*','.*2.*','.*2.*'],
    ['.*1.*0.*0.*0.*1.*','.*1.*0.*0.*0.*1.*','.*1.*0.*0.*0.*1.*','.*1.*0.*0.*0.*1.*'],
    ['.*6.*6.*6.*12.*12.*12.*18.*18.*18.*','.*6.*6.*6.*12.*12.*12.*18.*18.*18.*','.*6.*6.*6.*12.*12.*12.*18.*18.*18.*','.*6.*6.*6.*12.*12.*12.*18.*18.*18.*'],
    ['.*3.*5.*','.*3.*5.*','.*3.*5.*','.*3.*5.*'],
    ['.*gnikcar[tT].*ey[eE].*','.*gnikcar[tT].*ey[eE].*','.*gnikcar[tT].*ey[eE].*','.*gnikcar[tT].*ey[eE].*']
]


config_datasheet = r'./data_DG.xlsx'

In [3]:
raw = pd.read_excel(config_datasheet)
df = pd.DataFrame(raw, columns=["PD04", "PD05"])
df = df.dropna()
df = df.iloc[1:]

from scipy.stats import ttest_ind


print(df["PD04"].mean())
print(df["PD04"].std())
print(df["PD05"].mean())
print(df["PD05"].std())

nan
nan
nan
nan

In [18]:
df_matrix = []
raw = pd.read_excel(config_datasheet)

# load data
for row, _stuff in enumerate(config_algo_names):
    df_array = []
    for col, _stuff in enumerate(config_prefix):
        df = pd.DataFrame(raw, columns = [config_id_variable, 
                                          config_answer_variables[row][col], 
                                          config_time_variables[row][col],
                                          config_click_variables[row][col],])
        df = df.iloc[1:]
        df = df.dropna()
        df_array.append(df)
        
        
    df_matrix.append(df_array)
    print(df_matrix)

[[    CASE TI21_01  TIME011                          VC01_01
3    198  Arooba      8.0  224-406 195-99 210-236 415-652
8    211       3     58.0  224-406 195-99 210-236 415-652
14   224       3     30.0  224-406 195-99 210-236 415-652
17   231       3     85.0  224-406 195-99 210-236 415-652
18   232       3      5.0                  224-406 195-99
20   235       2    118.0  224-406 195-99 210-236 415-652
25   240       3     84.0  224-406 195-99 210-236 415-652 ,     CASE                                            TR21_01  TIME083  \
5    206                                                  1      3.0
10   214  it searches for a given number (here: 10) in t...    103.0
16   230                                                  3     66.0
23   238                                                  3    100.0

                            VA01_01
5   170-415 299-75 285-179 568-632
10                         170-415
16                         170-415
23  170-415 299-75 285-179 568-632   ,     CASE              BR21_01  TIME035                  VB01_01
2    182               Arooba      8.0  240-85 226-214 435-632
7    210                    4     99.0  240-85 226-214 435-662
9    212                    3    188.0          240-85 226-214
15   226                    3     23.0  240-85 226-214 435-662
19   234  Element not present    217.0  240-85 226-214 435-662 ,     CASE                                            BI21_01  TIME059  \
1    175                                             Arooba     12.0
6    209                                                  3    113.0
12   222                                      The position     116.0
13   223  The Code Produce The Position of number 10 (ar...     59.0
21   236                                                  3    119.0

                                            VD01_01
1           182-470 199-90 128-220 116-331 431-643
6   182-470 199-90 128-220 116-331 431-643 558-750
12                  182-470 199-90 128-220 116-331
13  182-470 199-90 128-220 116-331 431-643 558-750
21  182-470 199-90 128-220 116-331 431-643 558-750   ]]
[[    CASE TI21_01  TIME011                          VC01_01
3    198  Arooba      8.0  224-406 195-99 210-236 415-652
8    211       3     58.0  224-406 195-99 210-236 415-652
14   224       3     30.0  224-406 195-99 210-236 415-652
17   231       3     85.0  224-406 195-99 210-236 415-652
18   232       3      5.0                  224-406 195-99
20   235       2    118.0  224-406 195-99 210-236 415-652
25   240       3     84.0  224-406 195-99 210-236 415-652 ,     CASE                                            TR21_01  TIME083  \
5    206                                                  1      3.0
10   214  it searches for a given number (here: 10) in t...    103.0
16   230                                                  3     66.0
23   238                                                  3    100.0

                            VA01_01
5   170-415 299-75 285-179 568-632
10                         170-415
16                         170-415
23  170-415 299-75 285-179 568-632   ,     CASE              BR21_01  TIME035                  VB01_01
2    182               Arooba      8.0  240-85 226-214 435-632
7    210                    4     99.0  240-85 226-214 435-662
9    212                    3    188.0          240-85 226-214
15   226                    3     23.0  240-85 226-214 435-662
19   234  Element not present    217.0  240-85 226-214 435-662 ,     CASE                                            BI21_01  TIME059  \
1    175                                             Arooba     12.0
6    209                                                  3    113.0
12   222                                      The position     116.0
13   223  The Code Produce The Position of number 10 (ar...     59.0
21   236                                                  3    119.0

                                            VD01_01
1           182-470 199-90 128-220 116-331 431-643
6   182-470 199-90 128-220 116-331 431-643 558-750
12                  182-470 199-90 128-220 116-331
13  182-470 199-90 128-220 116-331 431-643 558-750
21  182-470 199-90 128-220 116-331 431-643 558-750   ], [Empty DataFrame
Columns: [CASE, TI22_01, TIME038, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR22_01, TIME014, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR22_01, TIME062, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI22_01, TIME086, VD01_01]
Index: []]]
[[    CASE TI21_01  TIME011                          VC01_01
3    198  Arooba      8.0  224-406 195-99 210-236 415-652
8    211       3     58.0  224-406 195-99 210-236 415-652
14   224       3     30.0  224-406 195-99 210-236 415-652
17   231       3     85.0  224-406 195-99 210-236 415-652
18   232       3      5.0                  224-406 195-99
20   235       2    118.0  224-406 195-99 210-236 415-652
25   240       3     84.0  224-406 195-99 210-236 415-652 ,     CASE                                            TR21_01  TIME083  \
5    206                                                  1      3.0
10   214  it searches for a given number (here: 10) in t...    103.0
16   230                                                  3     66.0
23   238                                                  3    100.0

                            VA01_01
5   170-415 299-75 285-179 568-632
10                         170-415
16                         170-415
23  170-415 299-75 285-179 568-632   ,     CASE              BR21_01  TIME035                  VB01_01
2    182               Arooba      8.0  240-85 226-214 435-632
7    210                    4     99.0  240-85 226-214 435-662
9    212                    3    188.0          240-85 226-214
15   226                    3     23.0  240-85 226-214 435-662
19   234  Element not present    217.0  240-85 226-214 435-662 ,     CASE                                            BI21_01  TIME059  \
1    175                                             Arooba     12.0
6    209                                                  3    113.0
12   222                                      The position     116.0
13   223  The Code Produce The Position of number 10 (ar...     59.0
21   236                                                  3    119.0

                                            VD01_01
1           182-470 199-90 128-220 116-331 431-643
6   182-470 199-90 128-220 116-331 431-643 558-750
12                  182-470 199-90 128-220 116-331
13  182-470 199-90 128-220 116-331 431-643 558-750
21  182-470 199-90 128-220 116-331 431-643 558-750   ], [Empty DataFrame
Columns: [CASE, TI22_01, TIME038, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR22_01, TIME014, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR22_01, TIME062, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI22_01, TIME086, VD01_01]
Index: []], [Empty DataFrame
Columns: [CASE, TI23_01, TIME065, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR23_01, TIME041, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR23_01, TIME086, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI23_01, TIME017, VD01_01]
Index: []]]
[[    CASE TI21_01  TIME011                          VC01_01
3    198  Arooba      8.0  224-406 195-99 210-236 415-652
8    211       3     58.0  224-406 195-99 210-236 415-652
14   224       3     30.0  224-406 195-99 210-236 415-652
17   231       3     85.0  224-406 195-99 210-236 415-652
18   232       3      5.0                  224-406 195-99
20   235       2    118.0  224-406 195-99 210-236 415-652
25   240       3     84.0  224-406 195-99 210-236 415-652 ,     CASE                                            TR21_01  TIME083  \
5    206                                                  1      3.0
10   214  it searches for a given number (here: 10) in t...    103.0
16   230                                                  3     66.0
23   238                                                  3    100.0

                            VA01_01
5   170-415 299-75 285-179 568-632
10                         170-415
16                         170-415
23  170-415 299-75 285-179 568-632   ,     CASE              BR21_01  TIME035                  VB01_01
2    182               Arooba      8.0  240-85 226-214 435-632
7    210                    4     99.0  240-85 226-214 435-662
9    212                    3    188.0          240-85 226-214
15   226                    3     23.0  240-85 226-214 435-662
19   234  Element not present    217.0  240-85 226-214 435-662 ,     CASE                                            BI21_01  TIME059  \
1    175                                             Arooba     12.0
6    209                                                  3    113.0
12   222                                      The position     116.0
13   223  The Code Produce The Position of number 10 (ar...     59.0
21   236                                                  3    119.0

                                            VD01_01
1           182-470 199-90 128-220 116-331 431-643
6   182-470 199-90 128-220 116-331 431-643 558-750
12                  182-470 199-90 128-220 116-331
13  182-470 199-90 128-220 116-331 431-643 558-750
21  182-470 199-90 128-220 116-331 431-643 558-750   ], [Empty DataFrame
Columns: [CASE, TI22_01, TIME038, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR22_01, TIME014, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR22_01, TIME062, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI22_01, TIME086, VD01_01]
Index: []], [Empty DataFrame
Columns: [CASE, TI23_01, TIME065, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR23_01, TIME041, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR23_01, TIME086, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI23_01, TIME017, VD01_01]
Index: []], [Empty DataFrame
Columns: [CASE, TI24_01, TIME092, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR24_01, TIME068, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR24_01, TIME020, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI24_01, TIME044, VD01_01]
Index: []]]
[[    CASE TI21_01  TIME011                          VC01_01
3    198  Arooba      8.0  224-406 195-99 210-236 415-652
8    211       3     58.0  224-406 195-99 210-236 415-652
14   224       3     30.0  224-406 195-99 210-236 415-652
17   231       3     85.0  224-406 195-99 210-236 415-652
18   232       3      5.0                  224-406 195-99
20   235       2    118.0  224-406 195-99 210-236 415-652
25   240       3     84.0  224-406 195-99 210-236 415-652 ,     CASE                                            TR21_01  TIME083  \
5    206                                                  1      3.0
10   214  it searches for a given number (here: 10) in t...    103.0
16   230                                                  3     66.0
23   238                                                  3    100.0

                            VA01_01
5   170-415 299-75 285-179 568-632
10                         170-415
16                         170-415
23  170-415 299-75 285-179 568-632   ,     CASE              BR21_01  TIME035                  VB01_01
2    182               Arooba      8.0  240-85 226-214 435-632
7    210                    4     99.0  240-85 226-214 435-662
9    212                    3    188.0          240-85 226-214
15   226                    3     23.0  240-85 226-214 435-662
19   234  Element not present    217.0  240-85 226-214 435-662 ,     CASE                                            BI21_01  TIME059  \
1    175                                             Arooba     12.0
6    209                                                  3    113.0
12   222                                      The position     116.0
13   223  The Code Produce The Position of number 10 (ar...     59.0
21   236                                                  3    119.0

                                            VD01_01
1           182-470 199-90 128-220 116-331 431-643
6   182-470 199-90 128-220 116-331 431-643 558-750
12                  182-470 199-90 128-220 116-331
13  182-470 199-90 128-220 116-331 431-643 558-750
21  182-470 199-90 128-220 116-331 431-643 558-750   ], [Empty DataFrame
Columns: [CASE, TI22_01, TIME038, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR22_01, TIME014, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR22_01, TIME062, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI22_01, TIME086, VD01_01]
Index: []], [Empty DataFrame
Columns: [CASE, TI23_01, TIME065, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR23_01, TIME041, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR23_01, TIME086, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI23_01, TIME017, VD01_01]
Index: []], [Empty DataFrame
Columns: [CASE, TI24_01, TIME092, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR24_01, TIME068, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR24_01, TIME020, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI24_01, TIME044, VD01_01]
Index: []], [    CASE     TI25_01  TIME023                          VC01_01
3    198      Arooba      5.0  224-406 195-99 210-236 415-652
8    211    '0100001    112.0  224-406 195-99 210-236 415-652
14   224       10001     86.0  224-406 195-99 210-236 415-652
17   231       10001     54.0  224-406 195-99 210-236 415-652
18   232       10001     19.0                  224-406 195-99
20   235  4 -> 2 ->     107.0  224-406 195-99 210-236 415-652
25   240       10001     98.0  224-406 195-99 210-236 415-652 ,     CASE                                            TR25_01  TIME095  \
5    206                                                  1      2.0
10   214  it divides the fiven int (here: 17) by 2 (with...     67.0
16   230                                              10001     21.0
23   238                                              10001     32.0

                            VA01_01
5   170-415 299-75 285-179 568-632
10                         170-415
16                         170-415
23  170-415 299-75 285-179 568-632   ,     CASE   BR25_01  TIME047                  VB01_01
2    182    Arooba     16.0  240-85 226-214 435-632
7    210  0, 2, 4     103.0  240-85 226-214 435-662
19   234         1    192.0  240-85 226-214 435-662 ,     CASE                                            BI25_01  TIME071  \
6    209                                              10001     88.0
12   222                                               1000    150.0
13   223  it print the number 17 in binary -> with mod 2...    117.0

                                            VD01_01
6   182-470 199-90 128-220 116-331 431-643 558-750
12                  182-470 199-90 128-220 116-331
13  182-470 199-90 128-220 116-331 431-643 558-750   ]]
[[    CASE TI21_01  TIME011                          VC01_01
3    198  Arooba      8.0  224-406 195-99 210-236 415-652
8    211       3     58.0  224-406 195-99 210-236 415-652
14   224       3     30.0  224-406 195-99 210-236 415-652
17   231       3     85.0  224-406 195-99 210-236 415-652
18   232       3      5.0                  224-406 195-99
20   235       2    118.0  224-406 195-99 210-236 415-652
25   240       3     84.0  224-406 195-99 210-236 415-652 ,     CASE                                            TR21_01  TIME083  \
5    206                                                  1      3.0
10   214  it searches for a given number (here: 10) in t...    103.0
16   230                                                  3     66.0
23   238                                                  3    100.0

                            VA01_01
5   170-415 299-75 285-179 568-632
10                         170-415
16                         170-415
23  170-415 299-75 285-179 568-632   ,     CASE              BR21_01  TIME035                  VB01_01
2    182               Arooba      8.0  240-85 226-214 435-632
7    210                    4     99.0  240-85 226-214 435-662
9    212                    3    188.0          240-85 226-214
15   226                    3     23.0  240-85 226-214 435-662
19   234  Element not present    217.0  240-85 226-214 435-662 ,     CASE                                            BI21_01  TIME059  \
1    175                                             Arooba     12.0
6    209                                                  3    113.0
12   222                                      The position     116.0
13   223  The Code Produce The Position of number 10 (ar...     59.0
21   236                                                  3    119.0

                                            VD01_01
1           182-470 199-90 128-220 116-331 431-643
6   182-470 199-90 128-220 116-331 431-643 558-750
12                  182-470 199-90 128-220 116-331
13  182-470 199-90 128-220 116-331 431-643 558-750
21  182-470 199-90 128-220 116-331 431-643 558-750   ], [Empty DataFrame
Columns: [CASE, TI22_01, TIME038, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR22_01, TIME014, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR22_01, TIME062, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI22_01, TIME086, VD01_01]
Index: []], [Empty DataFrame
Columns: [CASE, TI23_01, TIME065, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR23_01, TIME041, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR23_01, TIME086, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI23_01, TIME017, VD01_01]
Index: []], [Empty DataFrame
Columns: [CASE, TI24_01, TIME092, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR24_01, TIME068, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR24_01, TIME020, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI24_01, TIME044, VD01_01]
Index: []], [    CASE     TI25_01  TIME023                          VC01_01
3    198      Arooba      5.0  224-406 195-99 210-236 415-652
8    211    '0100001    112.0  224-406 195-99 210-236 415-652
14   224       10001     86.0  224-406 195-99 210-236 415-652
17   231       10001     54.0  224-406 195-99 210-236 415-652
18   232       10001     19.0                  224-406 195-99
20   235  4 -> 2 ->     107.0  224-406 195-99 210-236 415-652
25   240       10001     98.0  224-406 195-99 210-236 415-652 ,     CASE                                            TR25_01  TIME095  \
5    206                                                  1      2.0
10   214  it divides the fiven int (here: 17) by 2 (with...     67.0
16   230                                              10001     21.0
23   238                                              10001     32.0

                            VA01_01
5   170-415 299-75 285-179 568-632
10                         170-415
16                         170-415
23  170-415 299-75 285-179 568-632   ,     CASE   BR25_01  TIME047                  VB01_01
2    182    Arooba     16.0  240-85 226-214 435-632
7    210  0, 2, 4     103.0  240-85 226-214 435-662
19   234         1    192.0  240-85 226-214 435-662 ,     CASE                                            BI25_01  TIME071  \
6    209                                              10001     88.0
12   222                                               1000    150.0
13   223  it print the number 17 in binary -> with mod 2...    117.0

                                            VD01_01
6   182-470 199-90 128-220 116-331 431-643 558-750
12                  182-470 199-90 128-220 116-331
13  182-470 199-90 128-220 116-331 431-643 558-750   ], [Empty DataFrame
Columns: [CASE, TI26_01, TIME050, VC01_01]
Index: [], Empty DataFrame
Columns: [CASE, TR26_01, TIME026, VA01_01]
Index: [], Empty DataFrame
Columns: [CASE, BR26_01, TIME074, VB01_01]
Index: [], Empty DataFrame
Columns: [CASE, BI26_01, TIME098, VD01_01]
Index: []]]
[[    CASE TI21_01  TIME011                          VC01_01
3    198  Arooba      8.0  224-406 195-99 210-236 415-652
8    211       3     58.0  224-406 195-99 210-236 415-652

In [10]:
cols = ["id", "response_time", "correctness", "flag", "algo_name", "click_data"]
df_BU_R = pd.DataFrame(columns=cols)
df_BU_I = pd.DataFrame(columns=cols)
df_TD_R = pd.DataFrame(columns=cols)
df_TD_I = pd.DataFrame(columns=cols)

for row_idx, df_row in enumerate(df_matrix):
    algo_name = config_algo_names[row_idx]
    for col, df in enumerate(df_row): 
        pattern = config_answer_patterns[row_idx][col]
        regex = re.compile(pattern)
        
        for index, row in df.iterrows():

            id_value =  row["CASE"]
            response_time = int(row[config_time_variables[row_idx][col]])
            answer = row[config_answer_variables[row_idx][col]]
            click_data = row[config_click_variables[row_idx][col]]
            result = regex.match(str(answer))
            correctness = False
            
            if result is not None:
                correctness = True
                
            flag = ""
            data = pd.DataFrame([[id_value, response_time, correctness, flag, algo_name, click_data]], columns=cols)
                  
            if col == 0:
                df_BU_R = df_BU_R.append(data)
            elif col == 1:
                df_BU_I = df_BU_I.append(data)
            elif col == 2:
                df_TD_R = df_TD_R.append(data)
            else:
                df_TD_I = df_TD_I.append(data)

In [12]:
df_array_independent = [df_BU_R, df_BU_I, df_TD_R, df_TD_I]
print(df_array_independent)

[    id response_time correctness flag      algo_name  \
0  198             8       False        BinarySearch
0  211            58        True        BinarySearch
0  224            30        True        BinarySearch
0  231            85        True        BinarySearch
0  232             5        True        BinarySearch
0  235           118       False        BinarySearch
0  240            84        True        BinarySearch
0  198             5       False       IntegerBinary
0  211           112        True       IntegerBinary
0  224            86        True       IntegerBinary
0  231            54        True       IntegerBinary
0  232            19        True       IntegerBinary
0  235           107       False       IntegerBinary
0  240            98        True       IntegerBinary

                        click_data
0  224-406 195-99 210-236 415-652
0  224-406 195-99 210-236 415-652
0  224-406 195-99 210-236 415-652
0  224-406 195-99 210-236 415-652
0                  224-406 195-99
0  224-406 195-99 210-236 415-652
0  224-406 195-99 210-236 415-652
0  224-406 195-99 210-236 415-652
0  224-406 195-99 210-236 415-652
0  224-406 195-99 210-236 415-652
0  224-406 195-99 210-236 415-652
0                  224-406 195-99
0  224-406 195-99 210-236 415-652
0  224-406 195-99 210-236 415-652   ,     id response_time correctness flag      algo_name  \
0  206             3       False        BinarySearch
0  214           103        True        BinarySearch
0  230            66        True        BinarySearch
0  238           100        True        BinarySearch
0  206             2       False       IntegerBinary
0  214            67       False       IntegerBinary
0  230            21        True       IntegerBinary
0  238            32        True       IntegerBinary

                        click_data
0  170-415 299-75 285-179 568-632
0                         170-415
0                         170-415
0  170-415 299-75 285-179 568-632
0  170-415 299-75 285-179 568-632
0                         170-415
0                         170-415
0  170-415 299-75 285-179 568-632   ,     id response_time correctness flag      algo_name               click_data
0  182             8       False        BinarySearch  240-85 226-214 435-632
0  210            99       False        BinarySearch  240-85 226-214 435-662
0  212           188        True        BinarySearch          240-85 226-214
0  226            23        True        BinarySearch  240-85 226-214 435-662
0  234           217       False        BinarySearch  240-85 226-214 435-662
0  182            16       False       IntegerBinary  240-85 226-214 435-632
0  210           103       False       IntegerBinary  240-85 226-214 435-662
0  234           192       False       IntegerBinary  240-85 226-214 435-662 ,     id response_time correctness flag      algo_name  \
0  175            12       False        BinarySearch
0  209           113        True        BinarySearch
0  222           116       False        BinarySearch
0  223            59        True        BinarySearch
0  236           119        True        BinarySearch
0  209            88        True       IntegerBinary
0  222           150       False       IntegerBinary
0  223           117       False       IntegerBinary

                                        click_data
0          182-470 199-90 128-220 116-331 431-643
0  182-470 199-90 128-220 116-331 431-643 558-750
0                  182-470 199-90 128-220 116-331
0  182-470 199-90 128-220 116-331 431-643 558-750
0  182-470 199-90 128-220 116-331 431-643 558-750
0  182-470 199-90 128-220 116-331 431-643 558-750
0                  182-470 199-90 128-220 116-331
0  182-470 199-90 128-220 116-331 431-643 558-750   ]

In [7]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
cols = ["Subject","ProgrammingStyle", "Comprehension", "ResponseTime", "Algorithm", "Flag", "Correctness", "ClickData"]

def fill(list_data, dataframe, coding_style, comprehension_style):
    for idx, row in dataframe.iterrows():
        response_time = row["response_time"]
        algorithm = row["algo_name"]
        flag = row["flag"]
        click_data = row["click_data"]
        correctness = row["correctness"]
        id = row["id"]
        list_data.append([id,coding_style, comprehension_style, response_time, algorithm, flag, correctness, click_data])

data = []
fill(data, df_BU_R, "R", "BU")
fill(data, df_BU_I, "I", "BU")
fill(data, df_TD_R, "R", "TD")
fill(data, df_TD_I, "I", "TD")
df = pd.DataFrame(data, columns=cols)
print (df)
df.to_excel("./results/preprocessed.xlsx", index=False)

    Subject ProgrammingStyle Comprehension  ResponseTime      Algorithm Flag  \
0       198                R            BU             8   BinarySearch
1       211                R            BU            58   BinarySearch
2       224                R            BU            30   BinarySearch
3       231                R            BU            85   BinarySearch
4       232                R            BU             5   BinarySearch
5       235                R            BU           118   BinarySearch
6       240                R            BU            84   BinarySearch
7       198                R            BU             5  IntegerBinary
8       211                R            BU           112  IntegerBinary
9       224                R            BU            86  IntegerBinary
10      231                R            BU            54  IntegerBinary
11      232                R            BU            19  IntegerBinary
12      235                R            BU           107  IntegerBinary
13      240                R            BU            98  IntegerBinary
14      206                I            BU             3   BinarySearch
15      214                I            BU           103   BinarySearch
16      230                I            BU            66   BinarySearch
17      238                I            BU           100   BinarySearch
18      206                I            BU             2  IntegerBinary
19      214                I            BU            67  IntegerBinary
20      230                I            BU            21  IntegerBinary
21      238                I            BU            32  IntegerBinary
22      182                R            TD             8   BinarySearch
23      210                R            TD            99   BinarySearch
24      212                R            TD           188   BinarySearch
25      226                R            TD            23   BinarySearch
26      234                R            TD           217   BinarySearch
27      182                R            TD            16  IntegerBinary
28      210                R            TD           103  IntegerBinary
29      234                R            TD           192  IntegerBinary
30      175                I            TD            12   BinarySearch
31      209                I            TD           113   BinarySearch
32      222                I            TD           116   BinarySearch
33      223                I            TD            59   BinarySearch
34      236                I            TD           119   BinarySearch
35      209                I            TD            88  IntegerBinary
36      222                I            TD           150  IntegerBinary
37      223                I            TD           117  IntegerBinary

    Correctness                                        ClickData
0         False                  224-406 195-99 210-236 415-652
1          True                  224-406 195-99 210-236 415-652
2          True                  224-406 195-99 210-236 415-652
3          True                  224-406 195-99 210-236 415-652
4          True                                  224-406 195-99
5         False                  224-406 195-99 210-236 415-652
6          True                  224-406 195-99 210-236 415-652
7         False                  224-406 195-99 210-236 415-652
8          True                  224-406 195-99 210-236 415-652
9          True                  224-406 195-99 210-236 415-652
10         True                  224-406 195-99 210-236 415-652
11         True                                  224-406 195-99
12        False                  224-406 195-99 210-236 415-652
13         True                  224-406 195-99 210-236 415-652
14        False                  170-415 299-75 285-179 568-632
15         True                                         170-415
16         True                                         170-415
17         True                  170-415 299-75 285-179 568-632
18        False                  170-415 299-75 285-179 568-632
19        False                                         170-415
20         True                                         170-415
21         True                  170-415 299-75 285-179 568-632
22        False                          240-85 226-214 435-632
23        False                          240-85 226-214 435-662
24         True                                  240-85 226-214
25         True                          240-85 226-214 435-662
26        False                          240-85 226-214 435-662
27        False                          240-85 226-214 435-632
28        False                          240-85 226-214 435-662
29        False                          240-85 226-214 435-662
30        False          182-470 199-90 128-220 116-331 431-643
31         True  182-470 199-90 128-220 116-331 431-643 558-750
32        False                  182-470 199-90 128-220 116-331
33         True  182-470 199-90 128-220 116-331 431-643 558-750
34         True  182-470 199-90 128-220 116-331 431-643 558-750
35         True  182-470 199-90 128-220 116-331 431-643 558-750
36        False                  182-470 199-90 128-220 116-331
37        False  182-470 199-90 128-220 116-331 431-643 558-750